name: datalifecycle
channels:
  - conda-forge
  - defaults
  - huggingface
dependencies:
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blas=2.136
  - blas-devel=3.9.0
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - dataclasses=0.8
  - datasets=4.1.1
  - dill=0.4.0
  - expat=2.7.1
  - filelock=3.19.1
  - fonttools=4.60.1
  - freetype=2.14.1
  - fsspec=2025.9.0
  - gflags=2.2.2
  - glog=0.7.1
  - h2=4.3.0
  - hpack=4.1.0
  - huggingface_hub=0.29.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.15.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libparquet=16.1.0
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.10.0
  - matplotlib-base=3.10.6
  - munkres=1.1.4
  - ncurses=6.5
  - numexpr=2.11.0
  - numpy-base=2.0.1
  - openblas=0.3.30
  - openjpeg=2.5.3
  - openssl=3.5.4
  - orc=2.1.1
  - packaging=25.0
  - patsy=1.0.1
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - pyarrow-core=16.1.0
  - pycparser=2.22
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.3
  - requests=2.32.5
  - scipy=1.16.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.50.2
  - statsmodels=0.14.5
  - tk=8.6.15
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - attrs==25.3.0
      - boto3==1.40.51
      - botocore==1.40.51
      - frozenlist==1.7.0
      - halo==0.0.31
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - jmespath==1.0.1
      - log-symbols==0.0.14
      - multidict==6.6.4
      - multiprocess==0.70.16
      - numpy==2.3.3
      - pandas==2.3.3
      - parquet-tools==0.2.16
      - propcache==0.3.2
      - pyarrow==21.0.0
      - s3transfer==0.14.0
      - spinners==0.0.24
      - tabulate==0.9.0
      - termcolor==3.1.0
      - thrift==0.16.0
      - xxhash==3.6.0
      - yarl==1.20.1
prefix: /opt/miniconda3/envs/datalifecycle
